name: Advanced Codec Electron Build

on:
 workflow_dispatch:
 push:
   branches: [ main ]

jobs:
 build:
   runs-on: windows-latest
   steps:
   - uses: actions/checkout@v4

   - name: Set up Python
     uses: actions/setup-python@v5
     with:
       python-version: '3.11'

   - name: Install dependencies
     run: |
       python -m pip install --upgrade pip
       pip install setuptools wheel

   - name: Clone depot_tools
     run: |
       git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
       echo "${{ github.workspace }}/depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

   - name: Fetch and Build Chromium
     run: |
       fetch chromium
       cd src
       gn gen out/Release --args="is_official_build=true is_debug=false enable_platform_ac3_audio=true enable_platform_dts_audio=true use_proprietary_codecs=true enable_hevc_parser=true enable_dolby_vision_support=true media_codecs_focus_on_extensions=true"
       autoninja -C out/Release chrome

   - name: Build Electron
     run: |
       git clone https://github.com/electron/electron.git
       cd electron
       python script/bootstrap.py
       python script/configure.py -D use_proprietary_codecs=true
       python script/build.py

   - name: Create Release
     uses: softprops/action-gh-release@v2
     with:
       files: |
         electron/out/Release/electron.exe
         electron/out/Release/chrome_100_percent.pak
         electron/out/Release/resources.pak
         electron/out/Release/locales/*
       tag_name: v${{ github.run_number }}
       body: |
         Custom Electron build with advanced codec support
         - AC3 Audio
         - DTS Audio
         - Dolby Vision
         - HEVC Support
