name: Advanced Codec Electron Build
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 720  # Build can take several hours
    env:
      PYTHONIOENCODING: 'utf-8'
      DEPOT_TOOLS_WIN_TOOLCHAIN: '0'
      DEPOT_TOOLS_UPDATE: '0'
      CHROME_HEADLESS: '1'
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Visual Studio
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '17.8'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Configure System
      shell: pwsh
      run: |
        # Disable automatic pagefile management
        $computersys = Get-CimInstance Win32_ComputerSystem
        $computersys | Set-CimInstance -Property @{AutomaticManagedPagefile = $false}
        
        # Remove existing pagefile
        $pagefile = Get-CimInstance -ClassName Win32_PageFileSetting
        if ($pagefile) {
            Remove-CimInstance -InputObject $pagefile
        }
        
        # Create new pagefile with specified size
        $pageFilePath = "C:\pagefile.sys"
        $initialSize = [uint32]51200
        $maximumSize = [uint32]51200
        
        New-CimInstance -ClassName Win32_PageFileSetting -Property @{
            Name = $pageFilePath
            InitialSize = $initialSize
            MaximumSize = $maximumSize
        } -Namespace "root\cimv2"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel ninja
    
    - name: Clone depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "${{ github.workspace }}/depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Configure Windows Toolchain
      shell: pwsh
      run: |
        $env:DEPOT_TOOLS_WIN_TOOLCHAIN = "0"
        $env:GYP_MSVS_OVERRIDE_PATH = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        $env:DEPOT_TOOLS_UPDATE = "0"
        $env:DEPOT_TOOLS_WIN_TOOLCHAIN_BASE = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        
        # Verify Visual Studio installation
        if (!(Test-Path $env:GYP_MSVS_OVERRIDE_PATH)) {
            throw "Visual Studio path not found"
        }
    
    - name: Setup Git Cache
      shell: pwsh
      run: |
        # Create git cache directory
        New-Item -Path "C:\git-cache" -ItemType Directory -Force
        $env:DEPOT_TOOLS_WIN_TOOLCHAIN = "0"
        $env:GIT_CACHE_PATH = "C:\git-cache"
        
        # Configure git
        git config --global core.autocrlf false
        git config --global core.filemode false
        git config --global core.symlinks false
        git config --global branch.autosetuprebase always
        
    - name: Fetch Chromium
      shell: pwsh
      run: |
        # Set environment variables
        $env:DEPOT_TOOLS_WIN_TOOLCHAIN = "0"
        $env:DEPOT_TOOLS_UPDATE = "0"
        $env:GIT_CACHE_PATH = "C:\git-cache"
        
        # Initialize gclient
        gclient
        
        # Create .gclient file
        Set-Content -Path .gclient -Value @'
solutions = [
  {
    "name": "src",
    "url": "https://chromium.googlesource.com/chromium/src.git",
    "managed": False,
    "custom_deps": {},
    "custom_vars": {},
  },
]
'@
        
        # Sync with specific options
        gclient sync --no-history --with_branch_heads --with_tags
        
    - name: Configure and Build Chromium
      shell: pwsh
      run: |
        cd src
        $args = @'
        is_official_build = true
        is_debug = false
        use_proprietary_codecs = true
        ffmpeg_branding = "Chrome"
        media_use_ffmpeg = true
        enable_hevc_parser = true
        enable_dolby_vision_support = true
        proprietary_codecs = true
        enable_platform_hevc = true
        enable_platform_ac3_audio = true
        enable_platform_dts_audio = true
        media_codecs_focus_on_extensions = true
        is_component_build = false
        target_cpu = "x64"
        '@
        $args | Out-File -FilePath "args.gn" -Encoding utf8
        gn gen out/Release --args="$(Get-Content args.gn -Raw)"
        autoninja -C out/Release chrome
    
    - name: Build Electron
      run: |
        git clone https://github.com/electron/electron.git
        cd electron
        python script/bootstrap.py
        python script/configure.py -D use_proprietary_codecs=true -D ffmpeg_branding="Chrome"
        python script/build.py -c Release
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          electron/out/Release/electron.exe
          electron/out/Release/*.pak
          electron/out/Release/locales/*
          electron/out/Release/*.dll
        tag_name: v${{ github.run_number }}
        body: |
          Custom Electron build with advanced codec support:
          - AC3 Audio Support
          - DTS Audio Support
          - Dolby Vision Support
          - HEVC/H.265 Support
          
          Built with FFmpeg Chrome branding for enhanced codec support.
        draft: true
